apiVersion: apps/v1
kind: Deployment
metadata:
  name: xspends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xspends
  template:
    metadata:
      labels:
        app: xspends
    spec:
      containers:
      - name: xspends-container
        image: xspends-image  # You would replace this with the actual image name from your container registry.
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-key
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_DSN
