apiVersion: apps/v1
kind: Deployment
metadata:
  name: xspends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xspends
  template:
    metadata:
      labels:
        app: xspends
    spec:
      containers:
      - name: xspends-container
        image: xspends-image:TAG_PLACEHOLDER #<name>.azurecr.io/xspends:v0.1 # You would replace this with the actual image name from your container registry.
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: SWAGGER_HOST
          value: "localhost"  # Replace with your domain or public IP
        - name: SWAGGER_PORT
          value: "8080"  # Replace with your port if needed
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-key
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_DSN
