apiVersion: v1
kind: Service
metadata:
  name: xspends-service
spec:
  selector:
    app: xspends
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Change this if your app listens on a different port
  type: NodePort #LoadBalancer
